server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:../../bitespeed-config-repo/
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always